version: '3.8'

services:
  # Serviço PHP com Apache
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html  # Aponte para a pasta onde estão os arquivos PHP
    env_file:
      - .env # Carrega as variaveis do arquivo .env para Docker.
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${ROOT_USER}       # Usuário do MySQL
      PMA_PASSWORD: ${PASSWORD}   # Senha do MySQL
    depends_on:
      - db

volumes:
  db_data:
